"""made drinkorder dm id indexable

Revision ID: 4ce6067bb1f9
Revises: a67a660fcfdd
Create Date: 2021-11-09 12:25:40.405568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce6067bb1f9'
down_revision = 'a67a660fcfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_drink_meister_id'), ['drink_meister_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_drink_meister_id'))

    # ### end Alembic commands ###
