"""change drinkorder model

Revision ID: 6bff69b2c4ea
Revises: c17c79618180
Create Date: 2021-10-28 21:06:36.801895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bff69b2c4ea'
down_revision = 'c17c79618180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drinks_json', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location_json', sa.String(), nullable=True))
        batch_op.drop_column('drinks')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('drinks', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('location_json')
        batch_op.drop_column('drinks_json')

    # ### end Alembic commands ###
