"""added a field to a drink order to assign a dm

Revision ID: a67a660fcfdd
Revises: 6bff69b2c4ea
Create Date: 2021-11-09 00:03:16.269465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67a660fcfdd'
down_revision = '6bff69b2c4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_meister_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('drink_meister_id')

    # ### end Alembic commands ###
