"""sponsored_by

Revision ID: a97a79ad7a9c
Revises: d60399751928
Create Date: 2021-11-18 19:21:15.464719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a97a79ad7a9c"
down_revision = "d60399751928"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournaments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sponsored_by_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_users_sponsor", "users", ["sponsored_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournaments", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_sponsor", type_="foreignkey")
        batch_op.drop_column("sponsored_by_id")

    # ### end Alembic commands ###
