"""added current_hole

Revision ID: d1595dbab93d
Revises: 6bff69b2c4ea
Create Date: 2021-11-11 10:53:05.246119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1595dbab93d"
down_revision = "6bff69b2c4ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournament_enrollments",
        sa.Column("current_hole", sa.Integer()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournament_enrollments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tournament_enrollments_current_hole"))
    pass
    # ### end Alembic commands ###
