"""winning_distributions

Revision ID: d60399751928
Revises: 6bff69b2c4ea
Create Date: 2021-11-18 18:22:53.235780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60399751928'
down_revision = '6bff69b2c4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winning_distributions_json', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('winning_distributions_json')

    # ### end Alembic commands ###
