"""Added all fields to user model

Revision ID: e2a624875653
Revises: bcf8d8e1bd73
Create Date: 2021-10-07 17:29:28.010936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2a624875653"
down_revision = "bcf8d8e1bd73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthdate", sa.Date(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("PLAYER", "DRINK_MEISTER", "SPONSOR", "MANAGER", name="userrole"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("balance", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "balance")
    op.drop_column("users", "role")
    op.drop_column("users", "birthdate")
    # ### end Alembic commands ###
